import { describe, expect, it } from "vitest";
import type { RcMatch } from "./rcScan.ts";
import {
  CLAUDE_HOSTS,
  computeAppendContent,
  HOSTS_DEFAULT_BODY,
  renderClearanceSidecar,
  VAR_ALLOW_HOSTS,
  VAR_PERSONAL,
} from "./clearance.ts";

describe("HOSTS_DEFAULT_BODY", () => {
  it("contains both claude hosts uncommented under the section comment", () => {
    const lines = HOSTS_DEFAULT_BODY.split("\n");
    expect(lines).toContain("downloads.claude.ai");
    expect(lines).toContain("mcp-proxy.anthropic.com");
    expect(lines).toContain("# Claude Code runtime");
    // The optional extras stay commented out.
    expect(lines).toContain("#storage.googleapis.com");
  });
});

describe("computeAppendContent", () => {
  it("returns the input unchanged when both hosts are present (no-op)", () => {
    const existing = "downloads.claude.ai\nmcp-proxy.anthropic.com\n";
    expect(computeAppendContent(existing, CLAUDE_HOSTS)).toBe(existing);
  });

  it("appends only the missing host under the section comment", () => {
    const existing = "downloads.claude.ai\n";
    const next = computeAppendContent(existing, CLAUDE_HOSTS);
    expect(next).toBe(
      "downloads.claude.ai\n\n# Claude Code runtime\nmcp-proxy.anthropic.com\n",
    );
  });

  it("compares hosts case-insensitively", () => {
    const existing = "DOWNLOADS.CLAUDE.AI\nMCP-PROXY.ANTHROPIC.COM\n";
    expect(computeAppendContent(existing, CLAUDE_HOSTS)).toBe(existing);
  });

  it("re-adds a host that appears only in a comment", () => {
    const existing = "# downloads.claude.ai\nmcp-proxy.anthropic.com\n";
    const next = computeAppendContent(existing, CLAUDE_HOSTS);
    expect(next.split("\n")).toContain("downloads.claude.ai");
  });

  it("does not duplicate the section comment when it already exists", () => {
    const existing = "# Claude Code runtime\ndownloads.claude.ai\n";
    const next = computeAppendContent(existing, CLAUDE_HOSTS);
    const sectionComments = next
      .split("\n")
      .filter((l) => l.trim() === "# Claude Code runtime");
    expect(sectionComments).toHaveLength(1);
  });

  it("is idempotent: appending twice equals appending once (I2)", () => {
    const once = computeAppendContent("some.other.host\n", CLAUDE_HOSTS);
    expect(computeAppendContent(once, CLAUDE_HOSTS)).toBe(once);
  });

  it("normalizes a missing trailing newline before appending", () => {
    const next = computeAppendContent("some.other.host", CLAUDE_HOSTS);
    expect(next.startsWith("some.other.host\n")).toBe(true);
    expect(next.endsWith("\n")).toBe(true);
  });
});

describe("renderClearanceSidecar", () => {
  const noConflicts = new Map<string, RcMatch>();

  it("exports PERSONAL before ALLOW_HOSTS (expansion order is load-bearing)", () => {
    const body = renderClearanceSidecar(noConflicts);
    const personalAt = body.indexOf(`export ${VAR_PERSONAL}=1`);
    const allowAt = body.indexOf(`export ${VAR_ALLOW_HOSTS}=`);
    expect(personalAt).toBeGreaterThanOrEqual(0);
    expect(allowAt).toBeGreaterThan(personalAt);
  });

  it("emits the exact allow-hosts export line (I5 byte-compatibility)", () => {
    const body = renderClearanceSidecar(noConflicts);
    expect(body).toContain(
      'export CLEARANCE_ALLOW_HOSTS_FILES="$(npm root -g)/@clipboard-health/groundcrew/clearance-allow-hosts${CLEARANCE_PERSONAL_HOSTS:+:$HOME/.config/clearance/personal-allow-hosts}"',
    );
  });

  it("names crew-config in the header and never emits an em-dash", () => {
    const body = renderClearanceSidecar(noConflicts);
    expect(body).toContain("Generated by crew-config setup");
    expect(body).not.toContain("\u2014");
  });

  it("comments out a conflicting export with a note naming the rc location", () => {
    const conflicts = new Map<string, RcMatch>([
      [
        VAR_ALLOW_HOSTS,
        {
          item: VAR_ALLOW_HOSTS,
          file: "/home/u/.zshrc",
          line: 169,
          value: "/x",
        },
      ],
    ]);
    const body = renderClearanceSidecar(conflicts);
    expect(body).toContain("Already exported in /home/u/.zshrc:169");
    expect(body).toContain(`# export ${VAR_ALLOW_HOSTS}=`);
    expect(body).not.toContain(`\nexport ${VAR_ALLOW_HOSTS}=`);
    // The non-conflicting var is still exported live.
    expect(body).toContain(`export ${VAR_PERSONAL}=1`);
  });
});
