import type { RcMatch } from "./rcScan.ts";

export const VAR_PERSONAL = "CLEARANCE_PERSONAL_HOSTS";
export const VAR_ALLOW_HOSTS = "CLEARANCE_ALLOW_HOSTS_FILES";

export const CLAUDE_HOSTS: readonly string[] = [
  "downloads.claude.ai",
  "mcp-proxy.anthropic.com",
];

const SECTION_COMMENT = "# Claude Code runtime";

// `$(...)` expands at source-time so the absolute path stays current even
// when the user upgrades groundcrew via `npm update -g`. This export line is
// byte-identical to what the old plugin wrote (I5).
const ALLOW_HOSTS_VALUE =
  '"$(npm root -g)/@clipboard-health/groundcrew/clearance-allow-hosts' +
  '${CLEARANCE_PERSONAL_HOSTS:+:$HOME/.config/clearance/personal-allow-hosts}"';

export const HOSTS_DEFAULT_BODY = `# Personal egress allowlist, layered on top of groundcrew's starter file.
# Loaded when CLEARANCE_PERSONAL_HOSTS is set in your shell env.
# One host per line, # comments, *.example.com wildcards OK.

${SECTION_COMMENT}
downloads.claude.ai
mcp-proxy.anthropic.com

# Uncomment as needed
#storage.googleapis.com
#mcp.render.com
#api.x.ai
`;

/** The one-line rc snippet the user adds themselves (N3: rc files are never written). */
export const RC_SNIPPET = `for f in ~/.config/clearance/env.sh ~/.config/agent-safehouse/env.sh; do
  [ -f "$f" ] && . "$f"
done`;

function presentHosts(content: string): Set<string> {
  const hosts = new Set<string>();
  for (const line of content.split("\n")) {
    const stripped = line.trim();
    if (stripped.length === 0 || stripped.startsWith("#")) continue;
    hosts.add(stripped.toLowerCase());
  }
  return hosts;
}

/**
 * New hosts-file content with missing hosts appended, or `existing` unchanged
 * (same reference) when nothing is missing - callers skip the write on
 * identity, which is what makes a re-run a no-op (I2). Only uncommented lines
 * count as present; comparison is case-insensitive. Missing hosts are appended
 * at the end of the file, preceded by the section comment when the file does
 * not already contain it anywhere.
 */
export function computeAppendContent(
  existing: string,
  hostsToAdd: readonly string[],
): string {
  const already = presentHosts(existing);
  const missing = hostsToAdd.filter((h) => !already.has(h.toLowerCase()));
  if (missing.length === 0) return existing;

  const base = existing.replace(/\n+$/, "") + "\n";
  const needsSectionComment = !existing
    .split("\n")
    .some((line) => line.trim() === SECTION_COMMENT);

  const lines: string[] = [];
  if (needsSectionComment) {
    lines.push("", SECTION_COMMENT);
  }
  lines.push(...missing);
  return base + lines.join("\n") + "\n";
}

/**
 * Build the clearance env sidecar body. Order matters: CLEARANCE_PERSONAL_HOSTS
 * is exported FIRST because the `${...:+...}` expansion inside the ALLOW_HOSTS
 * value happens at export time, not lazily - reversed, the personal-file
 * branch silently drops out and only the baseline file is allowlisted.
 * A var already exported in the user's rc (smart-merge, F5) becomes a
 * commented copy with a note naming the rc file and line; the rc keeps owning it.
 */
export function renderClearanceSidecar(
  rcConflicts: ReadonlyMap<string, RcMatch>,
): string {
  const lines: string[] = [
    "# Generated by crew-config setup - safe to regenerate.",
    "# Source this from your shell rc:",
    "#   for f in ~/.config/clearance/env.sh ~/.config/agent-safehouse/env.sh; do",
    '#     [ -f "$f" ] && . "$f"',
    "#   done",
    "",
    `# ${VAR_PERSONAL} - opt into the personal allowlist append.`,
    `# Exported FIRST so the \${${VAR_PERSONAL}:+...} branch below resolves.`,
  ];
  const personal = rcConflicts.get(VAR_PERSONAL);
  if (personal !== undefined) {
    lines.push(
      `# Already exported in ${personal.file}:${personal.line} - sidecar leaving this alone.`,
      `# export ${VAR_PERSONAL}=1`,
    );
  } else {
    lines.push(`export ${VAR_PERSONAL}=1`);
  }
  lines.push("");
  lines.push(
    `# ${VAR_ALLOW_HOSTS} - groundcrew's baseline allowlist, plus your`,
    `# personal allowlist when ${VAR_PERSONAL} is set.`,
  );
  const allow = rcConflicts.get(VAR_ALLOW_HOSTS);
  if (allow !== undefined) {
    lines.push(
      `# Already exported in ${allow.file}:${allow.line} - sidecar leaving this alone.`,
      `# export ${VAR_ALLOW_HOSTS}=${ALLOW_HOSTS_VALUE}`,
    );
  } else {
    lines.push(`export ${VAR_ALLOW_HOSTS}=${ALLOW_HOSTS_VALUE}`);
  }
  lines.push("");
  return lines.join("\n");
}
