import { describe, expect, it } from "vitest";
import type { RcMatch } from "./rcScan.ts";
import {
  FN_SAFE,
  FN_SAFE_CLAUDE,
  OVERRIDES_STUB,
  renderSafehouseSidecar,
  VAR_APPEND_PROFILE,
} from "./safehouse.ts";

const OVERRIDES = "/home/u/.config/agent-safehouse/local-overrides.sb";
const NO_CONFLICTS = new Map<string, RcMatch>();

describe("renderSafehouseSidecar", () => {
  it("exports the append profile pointing at the overrides path", () => {
    const body = renderSafehouseSidecar(NO_CONFLICTS, OVERRIDES);
    expect(body).toContain(`export ${VAR_APPEND_PROFILE}="${OVERRIDES}"`);
  });

  it("emits the verbatim safe() wrapper (I5 byte-compatibility)", () => {
    const body = renderSafehouseSidecar(NO_CONFLICTS, OVERRIDES);
    expect(body).toContain(
      [
        "safe() {",
        "  safehouse \\",
        '    --append-profile="$SAFEHOUSE_APPEND_PROFILE" \\',
        '    "$@"',
        "}",
      ].join("\n"),
    );
  });

  it("emits the verbatim safe-claude() wrapper", () => {
    const body = renderSafehouseSidecar(NO_CONFLICTS, OVERRIDES);
    expect(body).toContain(
      [
        "safe-claude() {",
        '  safe claude --dangerously-skip-permissions "$@"',
        "}",
      ].join("\n"),
    );
  });

  it("names crew-config in the header and never emits an em-dash", () => {
    const body = renderSafehouseSidecar(NO_CONFLICTS, OVERRIDES);
    expect(body).toContain("Generated by crew-config setup");
    expect(body).not.toContain("\u2014");
  });

  it("comments the export with the rc's actual value on conflict", () => {
    const conflicts = new Map<string, RcMatch>([
      [
        VAR_APPEND_PROFILE,
        {
          item: VAR_APPEND_PROFILE,
          file: "/home/u/.zshrc",
          line: 42,
          value: "/custom/overrides.sb",
        },
      ],
    ]);
    const body = renderSafehouseSidecar(conflicts, OVERRIDES);
    expect(body).toContain("Already exported in /home/u/.zshrc:42");
    expect(body).toContain('(rc value: "/custom/overrides.sb")');
    expect(body).not.toContain(`\nexport ${VAR_APPEND_PROFILE}=`);
    // The functions are still emitted live.
    expect(body).toContain("safe() {");
  });

  it("falls back to a pointer note when the rc export has no extractable value", () => {
    const conflicts = new Map<string, RcMatch>([
      [
        VAR_APPEND_PROFILE,
        {
          item: VAR_APPEND_PROFILE,
          file: "/home/u/.zshrc",
          line: 7,
          value: null,
        },
      ],
    ]);
    const body = renderSafehouseSidecar(conflicts, OVERRIDES);
    expect(body).toContain('(rc value: "(see rc line for value)")');
  });

  it("comments out a conflicting function body line by line", () => {
    const conflicts = new Map<string, RcMatch>([
      [
        FN_SAFE,
        { item: FN_SAFE, file: "/home/u/.bashrc", line: 3, value: null },
      ],
    ]);
    const body = renderSafehouseSidecar(conflicts, OVERRIDES);
    expect(body).toContain("Already defined in /home/u/.bashrc:3");
    expect(body).toContain("# safe() {");
    // Only the commented copy exists: no uncommented definition line remains.
    expect(body).not.toContain("\nsafe() {");
    // safe-claude is unaffected.
    expect(body).toContain("\nsafe-claude() {");
    void FN_SAFE_CLAUDE;
  });
});

describe("OVERRIDES_STUB", () => {
  it("is a sandbox-exec comment-only stub naming crew-config", () => {
    expect(OVERRIDES_STUB).toContain("crew-config setup");
    // Every line is a `;;` comment or blank: an empty policy from day one.
    for (const line of OVERRIDES_STUB.split("\n")) {
      expect(line === "" || line.startsWith(";;")).toBe(true);
    }
  });
});
